services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./assets/:/www/assets
    ports:
      - 8081:8080
    environment:
      - INIT_ASSETS=1